name: Build and test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev
          wget -O - "https://apt.llvm.org/llvm.sh" | sudo bash -s 15
          sudo /usr/sbin/update-ccache-symlinks
          echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
          source ~/.bashrc

      - name: Build
        env:
          CONFIG_SITE: ${GITHUB_WORKSPACE}/depends/x86_64-pc-linux-gnu/share/config.site
          CXXFLAGS: -Wno-deprecated -Wno-unused-result
          CC: clang-15
          CXX: clang++-15
        run: |
          ./autogen.sh
          make -j$(nproc) -C depends NO_QT=1 NO_NATPMP=1 NO_UPNP=1 NO_ZMQ=1 NO_USDT=1
          ./configure --enable-debug
          make clean
          make -j$(nproc)

      - name: Publish artifact - linux
        uses: actions/upload-artifact@v4
        with:
          name: sequentia-linux
          path: |
            src/elementsd
            src/elements-cli
            src/elements-tx
            src/elements-util
            src/elements-wallet

  Test:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev
          wget -O - "https://apt.llvm.org/llvm.sh" | sudo bash -s 15

      - name: Configure
        env:
          CXXFLAGS: -Wno-deprecated -Wno-unused-result
          CC: clang-15
          CXX: clang++-15
        run: |
          ./autogen.sh
          ./configure

      - name: Run functional tests
        run: |
          ./test/functional/test_runner.py -j$(nproc) --timeout-factor=60 --failfast --ansi --combinedlogslen=4000
