name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev
          wget -O - "https://apt.llvm.org/llvm.sh" | sudo bash -s 18
          sudo /usr/sbin/update-ccache-symlinks
          echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
          source ~/.bashrc

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ runner.os }}
          max-size: 2G

      - name: Build
        env:
          BDB_PREFIX: '/home/runner/work/SEQ-Core-Elements/SEQ-Core-Elements/db4'
          NOWARN_CXXFLAGS: -Wno-deprecated -Wno-unused-result
          CC: clang-18
          CXX: clang++-18
        run: |
          ./autogen.sh
          CFLAGS='-Wno-error=implicit-function-declaration -Wno-deprecated-non-prototype' ./contrib/install_db4.sh .
          BDB_CFLAGS='-I${BDB_PREFIX}/include' BDB_LIBS='-L${BDB_PREFIX}/lib -ldb_cxx-4.8' ./configure --without-gui --without-natpmp --without-miniupnpc --disable-tests
          make clean
          make -j$(nproc)

      - name: Run tests
        run: |
          echo "Running tests"
          ./test/functional/test_runner.py

      - name: Publish artifact - linux
        uses: actions/upload-artifact@v4
        with:
          name: sequentia-linux
          path: |
            src/elementsd
            src/elements-cli
            src/elements-tx
            src/elements-util
            src/elements-wallet
