name: Sequentia Core CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run lint
        run: |
          ./ci/lint_run_all.sh
